ALTER TABLE retail_raw.NATION ADD CONSTRAINT FK_NATION_REGION 
FOREIGN KEY (N_REGIONKEY) REFERENCES retail_raw.REGION (R_REGIONKEY);

ALTER TABLE retail_raw.SUPPLIER ADD CONSTRAINT FK_SUPPLIER_NATION 
FOREIGN KEY (S_NATIONKEY) REFERENCES retail_raw.NATION (N_NATIONKEY);

ALTER TABLE retail_raw.CUSTOMER ADD CONSTRAINT FK_CUSTOMER_NATION 
FOREIGN KEY (C_NATIONKEY) REFERENCES retail_raw.NATION (N_NATIONKEY);

ALTER TABLE retail_raw.PARTSUPP ADD CONSTRAINT FK_PARTSUPP_PART 
FOREIGN KEY (PS_PARTKEY) REFERENCES retail_raw.PART (P_PARTKEY);

ALTER TABLE retail_raw.PARTSUPP ADD CONSTRAINT FK_PARTSUPP_SUPPLIER 
FOREIGN KEY (PS_SUPPKEY) REFERENCES retail_raw.SUPPLIER (S_SUPPKEY);

ALTER TABLE retail_raw.ORDERS ADD CONSTRAINT FK_ORDERS_CUSTOMER 
FOREIGN KEY (O_CUSTKEY) REFERENCES retail_raw.CUSTOMER (C_CUSTKEY);

ALTER TABLE retail_raw.LINEITEM ADD CONSTRAINT FK_LINEITEM_ORDER 
FOREIGN KEY (L_ORDERKEY) REFERENCES retail_raw.ORDERS (O_ORDERKEY);

ALTER TABLE retail_raw.LINEITEM ADD CONSTRAINT FK_LINEITEM_PARTSUPP 
FOREIGN KEY (L_PARTKEY, L_SUPPKEY) REFERENCES retail_raw.PARTSUPP (PS_PARTKEY, PS_SUPPKEY);



ALTER TABLE retail_staging.NATION ADD CONSTRAINT FK_NATION_REGION 
FOREIGN KEY (N_REGIONKEY) REFERENCES retail_staging.REGION (R_REGIONKEY);

ALTER TABLE retail_staging.SUPPLIER ADD CONSTRAINT FK_SUPPLIER_NATION 
FOREIGN KEY (S_NATIONKEY) REFERENCES retail_staging.NATION (N_NATIONKEY);

ALTER TABLE retail_staging.CUSTOMER ADD CONSTRAINT FK_CUSTOMER_NATION 
FOREIGN KEY (C_NATIONKEY) REFERENCES retail_staging.NATION (N_NATIONKEY);

ALTER TABLE retail_staging.PARTSUPP ADD CONSTRAINT FK_PARTSUPP_PART 
FOREIGN KEY (PS_PARTKEY) REFERENCES retail_staging.PART (P_PARTKEY);

ALTER TABLE retail_staging.PARTSUPP ADD CONSTRAINT FK_PARTSUPP_SUPPLIER 
FOREIGN KEY (PS_SUPPKEY) REFERENCES retail_staging.SUPPLIER (S_SUPPKEY);

ALTER TABLE retail_staging.ORDERS ADD CONSTRAINT FK_ORDERS_CUSTOMER 
FOREIGN KEY (O_CUSTKEY) REFERENCES retail_staging.CUSTOMER (C_CUSTKEY);

ALTER TABLE retail_staging.LINEITEM ADD CONSTRAINT FK_LINEITEM_ORDER 
FOREIGN KEY (L_ORDERKEY) REFERENCES retail_staging.ORDERS (O_ORDERKEY);

ALTER TABLE retail_staging.LINEITEM ADD CONSTRAINT FK_LINEITEM_PARTSUPP 
FOREIGN KEY (L_PARTKEY, L_SUPPKEY) REFERENCES retail_staging.PARTSUPP (PS_PARTKEY, PS_SUPPKEY);

