CREATE SCHEMA IF NOT EXISTS retail_raw;
CREATE SCHEMA IF NOT EXISTS retail_staging;

CREATE TABLE IF NOT EXISTS  retail_raw.CUSTOMER(
    C_CUSTKEY	BIGINT NOT NULL PRIMARY KEY,
    C_NAME	VARCHAR(25) NOT NULL,
    C_ADDRESS	VARCHAR(40) NOT NULL,
    C_NATIONKEY	BIGINT NOT NULL,
    C_PHONE	VARCHAR(15) NOT NULL,
    C_ACCTBAL	NUMERIC(12,2) NOT NULL,
    C_MKTSEGMENT	VARCHAR(10),
    C_COMMENT	VARCHAR(117)
);

CREATE TABLE IF NOT EXISTS  retail_raw.REGION(
    R_REGIONKEY	BIGINT NOT NULL PRIMARY KEY,
    R_NAME	VARCHAR(25) NOT NULL,
    R_COMMENT	VARCHAR(152)
);

CREATE TABLE IF NOT EXISTS  retail_raw.SUPPLIER(
    S_SUPPKEY	BIGINT NOT NULL PRIMARY KEY,
    S_NAME	VARCHAR(25) NOT NULL,
    S_ADDRESS	VARCHAR(40) NOT NULL,
    S_NATIONKEY	BIGINT NOT NULL,
    S_PHONE	VARCHAR(15) NOT NULL,
    S_ACCTBAL	NUMERIC(12,2) NOT NULL,
    S_COMMENT	VARCHAR(101)
);


CREATE TABLE IF NOT EXISTS  retail_raw.PART(
    P_PARTKEY	BIGINT NOT NULL PRIMARY KEY,
    P_NAME	VARCHAR(55) NOT NULL,
    P_MFGR	VARCHAR(25) NOT NULL,
    P_BRAND	VARCHAR(10) NOT NULL,
    P_TYPE	VARCHAR(25) NOT NULL,
    P_SIZE	BIGINT NOT NULL,
    P_CONTAINER	VARCHAR(10) NOT NULL,
    P_RETAILPRICE	NUMERIC(12,2) NOT NULL,
    P_COMMENT	VARCHAR(23)
);

CREATE TABLE IF NOT EXISTS retail_raw.LINEITEM(
    L_ORDERKEY	BIGINT NOT NULL,
    L_PARTKEY	BIGINT NOT NULL,
    L_SUPPKEY	BIGINT NOT NULL,
    L_LINENUMBER	BIGINT NOT NULL,
    L_QUANTITY	NUMERIC(12,2) NOT NULL,
    L_EXTENDEDPRICE	NUMERIC(12,2) NOT NULL,
    L_DISCOUNT	NUMERIC(12,2) NOT NULL,
    L_TAX	NUMERIC(12,2) NOT NULL,
    L_RETURNFLAG	VARCHAR(1) NOT NULL,
    L_LINESTATUS	VARCHAR(1) NOT NULL,
    L_SHIPDATE	DATE NOT NULL,
    L_COMMITDATE	DATE NOT NULL,
    L_RECEIPTDATE	DATE NOT NULL,
    L_SHIPINSTRUCT	VARCHAR(25) NOT NULL,
    L_SHIPMODE	VARCHAR(10) NOT NULL,  
    L_COMMENT	VARCHAR(44),
    PRIMARY KEY (L_ORDERKEY, L_LINENUMBER)
);

CREATE TABLE IF NOT EXISTS retail_raw.NATION(
    N_NATIONKEY	BIGINT NOT NULL PRIMARY KEY,
    N_NAME	VARCHAR(25) NOT NULL,
    N_REGIONKEY	BIGINT NOT NULL,
    N_COMMENT	VARCHAR(152)
);

CREATE TABLE IF NOT EXISTS retail_raw.PARTSUPP(
    PS_PARTKEY	BIGINT NOT NULL,
    PS_SUPPKEY	BIGINT NOT NULL,
    PS_AVAILQTY	BIGINT NOT NULL,
    PS_SUPPLYCOST	NUMERIC(12,2) NOT NULL,
    PS_COMMENT	VARCHAR(199),
    PRIMARY KEY (PS_PARTKEY, PS_SUPPKEY)
);

CREATE TABLE IF NOT EXISTS retail_raw.ORDERS(
    O_ORDERKEY	BIGINT PRIMARY KEY,
    O_CUSTKEY	BIGINT,
    O_ORDERSTATUS	VARCHAR(1),
    O_TOTALPRICE	NUMERIC(12,2),
    O_ORDERDATE	DATE,
    O_ORDERPRIORITY	VARCHAR(15),
    O_CLERK	VARCHAR(15),
    O_SHIPPRIORITY	BIGINT,
    O_COMMENT	VARCHAR(79)
);


CREATE TABLE IF NOT EXISTS  retail_staging.CUSTOMER(
    C_CUSTKEY	BIGINT NOT NULL PRIMARY KEY,
    C_NAME	VARCHAR(25) NOT NULL,
    C_ADDRESS	VARCHAR(40) NOT NULL,
    C_NATIONKEY	BIGINT NOT NULL,
    C_PHONE	VARCHAR(15) NOT NULL,
    C_ACCTBAL	NUMERIC(12,2) NOT NULL,
    C_MKTSEGMENT	VARCHAR(10),
    C_COMMENT	VARCHAR(117)
);

CREATE TABLE IF NOT EXISTS  retail_staging.REGION(
    R_REGIONKEY	BIGINT NOT NULL PRIMARY KEY,
    R_NAME	VARCHAR(25) NOT NULL,
    R_COMMENT	VARCHAR(152)
);

CREATE TABLE IF NOT EXISTS  retail_staging.SUPPLIER(
    S_SUPPKEY	BIGINT NOT NULL PRIMARY KEY,
    S_NAME	VARCHAR(25) NOT NULL,
    S_ADDRESS	VARCHAR(40) NOT NULL,
    S_NATIONKEY	BIGINT NOT NULL,
    S_PHONE	VARCHAR(15) NOT NULL,
    S_ACCTBAL	NUMERIC(12,2) NOT NULL,
    S_COMMENT	VARCHAR(101)
);


CREATE TABLE IF NOT EXISTS  retail_staging.PART(
    P_PARTKEY	BIGINT NOT NULL PRIMARY KEY,
    P_NAME	VARCHAR(55) NOT NULL,
    P_MFGR	VARCHAR(25) NOT NULL,
    P_BRAND	VARCHAR(10) NOT NULL,
    P_TYPE	VARCHAR(25) NOT NULL,
    P_SIZE	BIGINT NOT NULL,
    P_CONTAINER	VARCHAR(10) NOT NULL,
    P_RETAILPRICE	NUMERIC(12,2) NOT NULL,
    P_COMMENT	VARCHAR(23)
);

CREATE TABLE IF NOT EXISTS retail_staging.LINEITEM(
    L_ORDERKEY	BIGINT NOT NULL,
    L_PARTKEY	BIGINT NOT NULL,
    L_SUPPKEY	BIGINT NOT NULL,
    L_LINENUMBER	BIGINT NOT NULL,
    L_QUANTITY	NUMERIC(12,2) NOT NULL,
    L_EXTENDEDPRICE	NUMERIC(12,2) NOT NULL,
    L_DISCOUNT	NUMERIC(12,2) NOT NULL,
    L_TAX	NUMERIC(12,2) NOT NULL,
    L_RETURNFLAG	VARCHAR(1) NOT NULL,
    L_LINESTATUS	VARCHAR(1) NOT NULL,
    L_SHIPDATE	DATE NOT NULL,
    L_COMMITDATE	DATE NOT NULL,
    L_RECEIPTDATE	DATE NOT NULL,
    L_SHIPINSTRUCT	VARCHAR(25) NOT NULL,
    L_SHIPMODE	VARCHAR(10) NOT NULL,  
    L_COMMENT	VARCHAR(44),
    PRIMARY KEY (L_ORDERKEY, L_LINENUMBER)
);

CREATE TABLE IF NOT EXISTS retail_staging.NATION(
    N_NATIONKEY	BIGINT NOT NULL PRIMARY KEY,
    N_NAME	VARCHAR(25) NOT NULL,
    N_REGIONKEY	BIGINT NOT NULL,
    N_COMMENT	VARCHAR(152)
);

CREATE TABLE IF NOT EXISTS retail_staging.PARTSUPP(
    PS_PARTKEY	BIGINT NOT NULL,
    PS_SUPPKEY	BIGINT NOT NULL,
    PS_AVAILQTY	BIGINT NOT NULL,
    PS_SUPPLYCOST	NUMERIC(12,2) NOT NULL,
    PS_COMMENT	VARCHAR(199),
    PRIMARY KEY (PS_PARTKEY, PS_SUPPKEY)
);

CREATE TABLE IF NOT EXISTS retail_staging.ORDERS(
    O_ORDERKEY	BIGINT PRIMARY KEY,
    O_CUSTKEY	BIGINT,
    O_ORDERSTATUS	VARCHAR(1),
    O_TOTALPRICE	NUMERIC(12,2),
    O_ORDERDATE	DATE,
    O_ORDERPRIORITY	VARCHAR(15),
    O_CLERK	VARCHAR(15),
    O_SHIPPRIORITY	BIGINT,
    O_COMMENT	VARCHAR(79)
);


CREATE TABLE IF NOT EXISTS retail_staging.pipeline_watermarks (
    table_name TEXT PRIMARY KEY,
    last_loaded_value TEXT,
    last_loaded_at TIMESTAMP DEFAULT NOW()
);




ALTER TABLE retail_raw.NATION ADD CONSTRAINT FK_NATION_REGION 
FOREIGN KEY (N_REGIONKEY) REFERENCES retail_raw.REGION (R_REGIONKEY);

ALTER TABLE retail_raw.SUPPLIER ADD CONSTRAINT FK_SUPPLIER_NATION 
FOREIGN KEY (S_NATIONKEY) REFERENCES retail_raw.NATION (N_NATIONKEY);

ALTER TABLE retail_raw.CUSTOMER ADD CONSTRAINT FK_CUSTOMER_NATION 
FOREIGN KEY (C_NATIONKEY) REFERENCES retail_raw.NATION (N_NATIONKEY);

ALTER TABLE retail_raw.PARTSUPP ADD CONSTRAINT FK_PARTSUPP_PART 
FOREIGN KEY (PS_PARTKEY) REFERENCES retail_raw.PART (P_PARTKEY);

ALTER TABLE retail_raw.PARTSUPP ADD CONSTRAINT FK_PARTSUPP_SUPPLIER 
FOREIGN KEY (PS_SUPPKEY) REFERENCES retail_raw.SUPPLIER (S_SUPPKEY);

ALTER TABLE retail_raw.ORDERS ADD CONSTRAINT FK_ORDERS_CUSTOMER 
FOREIGN KEY (O_CUSTKEY) REFERENCES retail_raw.CUSTOMER (C_CUSTKEY);

ALTER TABLE retail_raw.LINEITEM ADD CONSTRAINT FK_LINEITEM_ORDER 
FOREIGN KEY (L_ORDERKEY) REFERENCES retail_raw.ORDERS (O_ORDERKEY);

ALTER TABLE retail_raw.LINEITEM ADD CONSTRAINT FK_LINEITEM_PARTSUPP 
FOREIGN KEY (L_PARTKEY, L_SUPPKEY) REFERENCES retail_raw.PARTSUPP (PS_PARTKEY, PS_SUPPKEY);



ALTER TABLE retail_staging.NATION ADD CONSTRAINT FK_NATION_REGION 
FOREIGN KEY (N_REGIONKEY) REFERENCES retail_staging.REGION (R_REGIONKEY);

ALTER TABLE retail_staging.SUPPLIER ADD CONSTRAINT FK_SUPPLIER_NATION 
FOREIGN KEY (S_NATIONKEY) REFERENCES retail_staging.NATION (N_NATIONKEY);

ALTER TABLE retail_staging.CUSTOMER ADD CONSTRAINT FK_CUSTOMER_NATION 
FOREIGN KEY (C_NATIONKEY) REFERENCES retail_staging.NATION (N_NATIONKEY);

ALTER TABLE retail_staging.PARTSUPP ADD CONSTRAINT FK_PARTSUPP_PART 
FOREIGN KEY (PS_PARTKEY) REFERENCES retail_staging.PART (P_PARTKEY);

ALTER TABLE retail_staging.PARTSUPP ADD CONSTRAINT FK_PARTSUPP_SUPPLIER 
FOREIGN KEY (PS_SUPPKEY) REFERENCES retail_staging.SUPPLIER (S_SUPPKEY);

ALTER TABLE retail_staging.ORDERS ADD CONSTRAINT FK_ORDERS_CUSTOMER 
FOREIGN KEY (O_CUSTKEY) REFERENCES retail_staging.CUSTOMER (C_CUSTKEY);

ALTER TABLE retail_staging.LINEITEM ADD CONSTRAINT FK_LINEITEM_ORDER 
FOREIGN KEY (L_ORDERKEY) REFERENCES retail_staging.ORDERS (O_ORDERKEY);

ALTER TABLE retail_staging.LINEITEM ADD CONSTRAINT FK_LINEITEM_PARTSUPP 
FOREIGN KEY (L_PARTKEY, L_SUPPKEY) REFERENCES retail_staging.PARTSUPP (PS_PARTKEY, PS_SUPPKEY);

